exports.lift = require("./anims/lift")
exports.drop = require("./anims/drop")
exports.move = require("./anims/move")
exports.attack = require("./anims/attack")
exports.fuse = require("./anims/fuse")
exports.flinch = require("./anims/flinch")
exports.fade = require("./anims/fade")
exports.phase = require("./anims/phase")
